function A = A_mat(h)
%A_MAT
%    A = A_MAT

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    03-Oct-2018 09:42:42

A = [1 h; 0 1]; %% TODO: FIX THIS

%A = reshape([0.0,0.0,0.0,0.0,0.0,0.0,9.81e2./1.0e2,9.81e2./5.0e1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[4,4]);
